# Min version you need for build project
version: '3.0'

services:
  main:
    # Name of main app container
    container_name: ${COMPOSE_PROJECT_NAME}
    build:
      context: .
    env_file:
      # File with environment variables
      - .env
    volumes:
      # Main app dir
      - .:/app
      # Virtual environment dir
      - /app/venv
    ports:
      # Reserve port for your needs (swagger for example)
      - ${PORT}:${PORT}
    # The starting command to launch the bot
    command: python3 main.py
    depends_on:
      # Your DBMS
      - ${DBMS}
    restart: always
  postgres:
    # Name of DBMS container
    container_name: ${COMPOSE_PROJECT_NAME}_db
    # Version of DBMS
    image: ${DBMS}:${DBMS_VERSION}
    env_file:
      # File with environment variables
      - .env
    environment:
      # Dir which writes DBMS data
      PG_DATA: /var/lib/postgresql/data
    ports:
      # Ports for DBMS (PostgreSQL by default)
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - /var/lib/postgresql/data
    restart: always
